title: "OSCAL Tools"
baseURL: https://pages.nist.gov/oscal-tools
relativeURLs: true
canonifyURLs: true
defaultContentLanguage: en
disableAliases: false
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "uswds"
googleAnalytics: UA-42404149-54
enableGitInfo: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      autoHeadingID: true
#      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
params:
  header:
    project_shortname: "OSCAL Tools"
    project_name: "OSCAL: the Open Security Controls Assessment Language - Tools"
  page_repo_path: https://github.com/usnistgov/oscal-tools/tree/main/docs/content
  searchAffiliate: oscal
  sidenav:
#    debug: true
  
menu:
  primary:
  - name: "OSCAL"
    url: "https://pages.nist.gov/OSCAL"
    weight: 99
  secondary:
  - name: Github
    url: https://github.com/usnistgov/oscal-tools
    weight: 90
module:
  mounts:
#  - source: content
#    target: content
  - source: static
    target: static
#  - source: ../xml
#    target: static/artifacts/xml
#  - source: ../json
#    target: static/artifacts/json
#  - source: ../content
#    target: static/artifacts/content
#  - source: layouts
#    target: layouts
#  - source: data
#    target: data
#  - source: assets
#    target: assets
#  - source: i18n
#    target: i18n
  - source: archetypes
    target: archetypes
